# Generated by Django 3.2.13 on 2024-07-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240710_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='created_at',
            new_name='created',
        ),
    ]
